version: '3'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./data/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - 5432:5432
  spark:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      -8080:8080
    depends_on:
      - db
  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
    depends_on:
      - spark
    links:
      - spark
  embulk:
    image: embulk/embulk
    volumes:
      - ./data:/data
      - ./config:/config
      - ./output:/output
      - .scripts:/scripts
    depends_on:
      - db
  scheduler:
    image: bitnami/spark:latest
    volumes:
      - ./scripts:/scripts
      - ./config:/config
      - ./output:/output
    depends_on:
      - embulk
    entrypoint: ["/bin/bash", "-c", "spark-submit /scripts/spark_orchestrator.py"]